import { FaAngleDown, FaCheck, FaTimes } from "react-icons/fa";

export default [
  {
    id: 1,
    plan: "Basic Plan",
    hairCut: "Standard Hair Cut",
    price: "$20",
    icon: <FaAngleDown />,
    flag: "Basic",
    list : [
      "Basic Hair Cut",
      "Beard Shave",
      "Hair Wash",
      "Basic Head Rub",
      "Hair Dyeing",
      "Head Massage",
      "Face Exfoliation",
      "Facial retinol therapy",
    ],
    iconList: [
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaTimes color="red"/>,
      <FaTimes color="red"/>,
      <FaTimes color="red"/>,
    ],
    cName: 'first-plan',
    btnClass: 'btn-basic',
  },
  {
    id: 2,
    plan: "Popular Plan",
    hairCut: "Medium Hair Cut",
    price: "$40",
    icon: <FaAngleDown />,
    flag: "HOT!!",
    list :  [
      "Basic Hair Cut",
      "Beard Shave",
      "Hair Wash",
      "Basic Head Rub",
      "Hair Dyeing",
      "Head Massage",
      "Face Exfoliation",
      "Facial retinol therapy",
    ],
    iconList: [
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaTimes color="red" />,
      <FaTimes color="red" />,
    ],
    cName: 'second-plan',
  },
  {
    id: 3,
    plan: "Premium Plan",
    hairCut: "Premium Hair Cut",
    price: "$60",
    flag: "Premium",
    icon: <FaAngleDown />,
    list : [
      "Basic Hair Cut",
      "Beard Shave",
      "Hair Wash",
      "Basic Head Rub",
      "Hair Dyeing",
      "Head Massage",
      "Face Exfoliation",
      "Facial retinol therapy",
    ],
    iconList : [
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaCheck />,
      <FaCheck/>,
      <FaCheck />,
      <FaCheck />,
    ],
    cName: 'third-plan',
    btnClass: 'btn-premium',
  }
]